language: java
jdk:
  - oraclejdk8

branches:
  only:
    - master
    - develop

cache:
  directories:
    - $HOME/.m2

install:
  - mvn -B -V -e -q -DskipTests -Dmaven.javadoc.skip install

before_script:
  - echo "changeLogFile=de/vinado/wicket/participate/db/liquibase/changelog.xml" > src/main/resources/liquibase.properties

script:
  - mvn -B -q test

notifications:
  email:
    on_failure: never
    on_success: never
