dist: trusty
language: java
jdk:
  - oraclejdk8

services:
  - docker

cache:
  directories:
    - $HOME/.m2

env:
  - DOCKER_REPO_SLUG=kchwr/participate

install:
  - mvn -B -V -DskipTests=true -Dmaven.javadoc.skip=true install

before_script:
  - echo "changeLogFile=de/vinado/wicket/participate/db/liquibase/changelog.xml" > src/main/resources/liquibase.properties

script:
  - mvn -B test

deploy:
  - provider: script
    script: bash scripts/docker-push.sh
    on:
      tags: true

notifications:
  email:
    recipients:
      - me@vinado.de
    on_success: never
    on_failure: always
