version: '3'

services:
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: participate
      MYSQL_USER: participate
      MYSQL_PASSWORD: participate

  fakesmtp:
    image: amontaigu/fakesmtp
    ports:
      - "587:25"
    volumes:
      - $HOME/received-emails/:/var/mail
