services:
  database:
    image: mariadb:10.2
    ports:
      - "3306:3306"
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: participate
      MARIADB_USER: participate
      MARIADB_PASSWORD: participate

  fakesmtp:
    image: ghusta/fakesmtp:2.3-jre17
    ports:
      - "587:25"
    volumes:
      - $HOME/received-emails/:/var/mail
