version: '3'

networks:
    participate:

services:
    database:
        image: mysql:5.7
        container_name: participate-db
        restart: always
        networks:
        - participate
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: participate
            MYSQL_USER: participate
            MYSQL_PASSWORD: participate

    participate:
        depends_on:
        - database
        image: kammerchor-wernigerode/participate:latest
        container_name: participate
        restart: always
        networks:
        - participate
        ports:
        - 8080:8080
        links:
        - 'database:mysql'
        environment:
            APPLICATION_NAME: 'Application Name'
            APPLICATION_CUSTOMER: 'Application Customer'
            APPLICATION_PASSWORD: 'application_password'
            DATABASE_HOST: 'mysql'
            DATABASE_PORT: 3306
            DATABASE_NAME: 'participate'
            DATABASE_USER: 'participate'
            DATABASE_PASSWORD: 'participate'
            MAIL_HOST: 'mail.domain.tld'
            MAIL_PORT: 587
            MAIL_USER: 'mail.user@domain.tld'
            MAIL_PASSWORD: 'mail_password'
            MAIL_FROM: 'no-reply@domain.tld'
