spring:
  application:
    name: ${APPLICATION_NAME:Participate}

  profiles:
    default: metrics
    group:
      keycloak: oidc,oauth2

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: true
    properties:
      hibernate.format_sql: true

  datasource:
    url: jdbc:mariadb://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:participate}?allowPublicKeyRetrieval=true&sslMode=disable
    username: ${DATABASE_USER:participate}
    password: ${DATABASE_PASSWORD:participate}
    hikari.max-lifetime: 600000

  liquibase:
    change-log: 'classpath:/de/vinado/wicket/participate/db/liquibase/changelog.xml'

  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:587}
    test-connection: true
    properties:
      mail.smtp.localhost: ${SMTP_HELO:localhost}
      mail.from: ${MAIL_FROM:smtp@example.com}
      mail.reply-to: ${MAIL_REPLY_TO:no-reply@example.com}

app:
  version: "^project.version^"
  base-url: ${BASE_URL:http://localhost:8080}
  customer: ${APPLICATION_CUSTOMER:Default Customer}
  participate-password: ${APPLICATION_PASSWORD:f0rmp4ss}
  deadline-offset: ${DEADLINE_OFFSET:-1}
  organization-responsible: ${RESPONSIBLE_ORGANIZATION}
  sleeping-place-responsible: ${RESPONSIBLE_SLEEPING_PLACE}
  crypto:
    session-secret: ${CRYPTO_SESSION_SECRET:}
    pbe-salt: ${CRYPTO_PBE_SALT:}
    pbe-iteration-count: ${CRYPTO_PBE_ITERATION_COUNT:1000}
  mail:
    footer: ${spring.application.name}
    sender: ${spring.mail.properties.mail.from}
    reply-to: ${spring.mail.properties.mail.reply-to}
  wicket:
    runtime-configuration: DEPLOYMENT
  google-calendar:
    source: foo

  features:
    remind-overdue:
      enabled: ${OVERDUE_ENABLED:false}
      cron-expression: ${OVERDUE_CRON:0 0 9 ? * SUN}
      offset: ${OVERDUE_OFFSET:14}
    scores-manager-notification:
      enabled: ${SCORES_MANAGER_ENABLED:false}
      cron-expression: ${SCORES_MANAGER_CRON:0 0 9 ? * SUN}
      offset: ${SCORES_MANAGER_OFFSET:7}
      scores-manager-email: ${SCORES_MANAGER_EMAIL}

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8081}
  endpoints:
    web:
      exposure:
        include: health
