spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/participate?allowPublicKeyRetrieval=true&sslMode=disable
    username: participate
    password: participate
    hikari.max-lifetime: 600000
