spring:
  application:
    name: ${APPLICATION_NAME}

  jpa:
    database: MYSQL
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect

  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME}?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: 'classpath:/de/vinado/wicket/participate/db/liquibase/changelog.xml'

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.from: ${MAIL_FROM}

app:
  base-url: ${BASE_URL}
  customer: ${APPLICATION_CUSTOMER}
  version: @project.version@
  participate-password: ${APPLICATION_PASSWORD}
  development-mode: false
  mail:
    footer: ${spring.application.name}
    sender: ${spring.mail.properties.mail.smtp.from}

logging:
  file: 'target/logs/wicket.log'
