server:
  servlet:
    session.cookie.path: /_

spring:
  application:
    name: ${APPLICATION_NAME:Participate}

  profiles:
    default: metrics

  jpa:
    database: MYSQL
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: validate
    show-sql: false
    open-in-view: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect

  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:participate}?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DATABASE_USER:participate}
    password: ${DATABASE_PASSWORD:participate}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari.max-lifetime: 600000

  liquibase:
    change-log: 'classpath:/de/vinado/wicket/participate/db/liquibase/changelog.xml'

  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:587}
    test-connection: true
    properties:
      mail.smtp.localhost: ${SMTP_HELO:localhost}
      mail.from: ${MAIL_FROM:smtp@example.com}
      mail.reply-to: ${MAIL_REPLY_TO:no-reply@example.com}

javamail:
  dkim:
    # ${JAVAMAIL_DKIM_SELECTOR}._domainkey.${JAVAMAIL_DKIM_DOMAIN}
    signing-domain: ${MAIL_DKIM_SIGNING_DOMAIN:}
    selector: ${MAIL_DKIM_SELECTOR:}
    private-key: ${MAIL_DKIM_PRIVATE_KEY_URI:}
    signer:
      identity: ${MAIL_DKIM_SIGNER_IDENTITY:}
      header-canonicalization: ${MAIL_DKIM_SIGNER_HEADER_CANONICALIZATION:SIMPLE}
      body-canonicalization: ${MAIL_DKIM_SIGNER_BODY_CANONICALIZATION:RELAXED}
      check-domain-key: ${MAIL_DKIM_SIGNER_CHECK_DOMAIN:true}
      signing-algorithm: ${MAIL_DKIM_SIGNER_SIGNING_ALGORITHM:SHA256_WITH_RSA}
      length-param: ${MAIL_DKIM_SIGNER_LENGTH_PARAM:true}
      copy-header-fields: ${MAIL_DKIM_SIGNER_COPY_HEADER_FIELDS:false}
  concurrent:
    enabled: ${MAIL_CONCURRENT_ENABLED:false}
    batch-size: ${MAIL_CONCURRENT_BATCH_SIZE:20}
    cooldown-millis: ${MAIL_CONCURRENT_COOLDOWN_MILLIS:20000}

app:
  version: "^project.version^"
  base-url: ${BASE_URL:http://localhost:8080}
  customer: ${APPLICATION_CUSTOMER:Default Customer}
  participate-password: ${APPLICATION_PASSWORD:f0rmp4ss}
  deadline-offset: ${DEADLINE_OFFSET:-1}
  organization-responsible: ${RESPONSIBLE_ORGANIZATION}
  sleeping-place-responsible: ${RESPONSIBLE_SLEEPING_PLACE}
  crypto:
    session-secret: ${CRYPTO_SESSION_SECRET:}
    pbe-salt: ${CRYPTO_PBE_SALT:}
    pbe-iteration-count: ${CRYPTO_PBE_ITERATION_COUNT:1000}
  mail:
    footer: ${spring.application.name}
    sender: ${spring.mail.properties.mail.from}
    reply-to: ${spring.mail.properties.mail.reply-to}
  wicket:
    runtime-configuration: DEPLOYMENT

  features:
    remind-overdue:
      enabled: ${OVERDUE_ENABLED:false}
      cron-expression: ${OVERDUE_CRON:0 0 9 ? * SUN}
      offset: ${OVERDUE_OFFSET:14}
    scores-manager-notification:
      enabled: ${SCORES_MANAGER_ENABLED:false}
      cron-expression: ${SCORES_MANAGER_CRON:0 0 9 ? * SUN}
      offset: ${SCORES_MANAGER_OFFSET:7}
      scores-manager-email: ${SCORES_MANAGER_EMAIL}

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8081}
  endpoints:
    web:
      exposure:
        include: health
