spring:
    application:
        name: ${APPLICATION_NAME}

    jpa:
        database: mysql
        hibernate:
            naming:
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
            ddl-auto: validate
        show-sql: false
        properties:
            hibernate.format_sql: true
            hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

    datasource:
        url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
        driver-class-name: com.mysql.jdbc.Driver

    liquibase:
        change-log: 'classpath:/de/vinado/wicket/participate/db/liquibase/changelog.xml'

    mail:
        host: ${MAIL_HOST}
        port: ${MAIL_PORT}
        username: ${MAIL_USER}
        password: ${MAIL_PASSWORD}
        properties:
            mail.smtp.starttls.enable: true
            mail.smtp.from: ${MAIL_FROM}

app:
    customer: ${APPLICATION_CUSTOMER}
    version: @project.version@
    participate-password: ${APPLICATION_PASSWORD}
    development-mode: false

    mail:
        footer: ${java.specification.name}
        sender: ${spring.mail.properties.mail.smtp.from}

logging:
    file: 'target/logs/wicket.log'
