spring:
  application:
    name: Participate

  profiles:
    group:
      oidc: oauth2

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: true
    properties:
      hibernate.format_sql: true

  datasource:
    url: jdbc:mariadb://localhost:3306/participate?allowPublicKeyRetrieval=true&sslMode=disable
    username: participate
    password: participate
    hikari.max-lifetime: 600000

  liquibase:
    change-log: 'classpath:/de/vinado/wicket/participate/db/liquibase/changelog.xml'

  mail:
    host: localhost
    port: 587
    username:
    password:
    test-connection: true
    properties:
      mail.smtp.auth: false
      mail.smtp.localhost: localhost
      mail.from: smtp@example.com
      mail.reply-to: no-reply@example.com
      mail.smtp.starttls.enable: false

app:
  version: "^project.version^"
  base-url: http://localhost:8080
  customer: Default Customer
  participate-password: f0rmp4ss
  deadline-offset: -1
  organization-responsible:
  sleeping-place-responsible:
  crypto:
    session-secret:
    pbe-salt:
    pbe-iteration-count: 1000
  mail:
    footer: ${spring.application.name}
    sender: ${spring.mail.properties.mail.from}
    reply-to: ${spring.mail.properties.mail.reply-to}
  notification:
    email:
      sender: ${spring.mail.properties.mail.from}
      reply-to: ${spring.mail.properties.mail.reply-to}
  wicket:
    runtime-configuration: DEPLOYMENT
  google-calendar:
    source: foo

  features:
    remind-overdue:
      enabled: false
      cron-expression: 0 0 9 ? * SUN
      offset: 14
    scores-manager-notification:
      enabled: false
      cron-expression: 0 0 9 ? * SUN
      offset: 7
      scores-manager-email:

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health
