spring:
  docker.compose:
    enabled: true
    lifecycle-management: start_only
    readiness:
      wait: only_if_started
    start:
      skip: never
      log-level: debug

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9080/realms/local
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: participate
            client-secret: HizmgIafi7qLMZCg4ywlUVNkl6BJZM3r
            scope: openid, email, profile

app:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            account-url: ${spring.security.oauth2.client.provider.keycloak.issuer-uri}/account
            roles-json-path: $.resource_access.${spring.security.oauth2.client.registration.keycloak.client-id}.roles[*]

wicket:
  management:
    runtime-configuration: development
