spring:
  application:
    name: participate

  profiles:
    default: postgresql

  main:
    banner-mode: off

  docker.compose.enabled: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
