attendance.full=
attendance.fromTo=From ${from} to ${to}
attendance.from=From ${from}
attendance.to=Until ${to}
attendees=Attendees
attendee.accommodationNeeded=Needs accommodation
attendee.byCar=Has car
attendee.comment=Comment
attendee.offeredBeds=Beds offered
attendee.presence=Presence
attendee.presenceNote=Note
AttendeeForm.from=From
AttendeeForm.to=To
back=Back
close=Close
count=Count
dayPeriod.SUNDAY.MORNING=Sunday morning
dayPeriod.SUNDAY.AFTERNOON=Sunday afternoon
dayPeriod.SUNDAY.EVENING=Sunday evening
dayPeriod.SUNDAY.NIGHT=Sunday night
dayPeriod.MONDAY.MORNING=Monday morning
dayPeriod.MONDAY.AFTERNOON=Monday afternoon
dayPeriod.MONDAY.EVENING=Monday evening
dayPeriod.MONDAY.NIGHT=Monday night
dayPeriod.TUESDAY.MORNING=Tuesday morning
dayPeriod.TUESDAY.AFTERNOON=Tuesday afternoon
dayPeriod.TUESDAY.EVENING=Tuesday evening
dayPeriod.TUESDAY.NIGHT=Tuesday night
dayPeriod.WEDNESDAY.MORNING=Wednesday morning
dayPeriod.WEDNESDAY.AFTERNOON=Wednesday afternoon
dayPeriod.WEDNESDAY.EVENING=Wednesday evening
dayPeriod.WEDNESDAY.NIGHT=Wednesday night
dayPeriod.THURSDAY.MORNING=Thursday morning
dayPeriod.THURSDAY.AFTERNOON=Thursday afternoon
dayPeriod.THURSDAY.EVENING=Thursday evening
dayPeriod.THURSDAY.NIGHT=Thursday night
dayPeriod.FRIDAY.MORNING=Friday morning
dayPeriod.FRIDAY.AFTERNOON=Friday afternoon
dayPeriod.FRIDAY.EVENING=Friday evening
dayPeriod.FRIDAY.NIGHT=Friday night
dayPeriod.SATURDAY.MORNING=Saturday morning
dayPeriod.SATURDAY.AFTERNOON=Saturday afternoon
dayPeriod.SATURDAY.EVENING=Saturday evening
dayPeriod.SATURDAY.NIGHT=Saturday night
date=Date
Dropdown.toggle=Toggle Dropdown
accountSettingsLink.body=Account Settings
EmailAddressColumn.copy.onSuccess=Email addresses has been copied to the clipboard
event=Event
event.adp.abbrev=Ac/De/Pe
event.adp.full=Accepted/Declined/Pending
event.createdDate=Created
event.date=Date
event.description=Description
event.location=Location
event.summary=Name
EventCreationForm.submit.success=A new event has been added
EventEditForm.submit.success=The event was successfully edited
EventForm.description=Add description
EventForm.details=Details
EventForm.endDateTime=End date
EventForm.location=Add location
EventForm.startDateTime=Start date
EventForm.summary=Add summary
EventForm.to=to
EventPanel.event.actions=Event actions
EventPanel.event.details=Show Event Summary
EventPanel.event.edit=Edit Event
EventTablePanel.create=Create Event
events=Events
InvitationStatus.ACCEPTED=Accepted
InvitationStatus.DECLINED=Declined
InvitationStatus.PENDING=Pending
InvitationStatus.TENTATIVE=Tentative
InvitationStatus.UNINVITED=Uninvited
InvitationStatusFilter.btnGroup.0.label=Invitation status toggle button group 1
InvitationStatusFilter.btnGroup.1.label=Invitation status toggle button group 2
InvitationStatusFilter.btnGroup.2.label=Invitation status toggle button group 3
musician.voice=Voice
NavigatorLabel=${from}–${to} of ${of}
PageSizeSelector.label=Rows per page
PageSizeSelector.option.all=All
person.emailAddress=Email
person.name=Name
persons=People
save=Save
signOutLink.body=Sign Out
TabbedPanel.CSS.selected=active
Voice.ALTO=Alto
Voice.BASS=Bass
Voice.SOPRANO=Soprano
Voice.TENOR=Tenor
