date=Date
accountSettingsLink.body=Account Settings
event=Event
event.adp.abbrev=Ac/De/Pe
event.adp.full=Accepted/Declined/Pending
event.location=Location
event.summary=Name
events=Events
InvitationStatus.ACCEPTED=Accepted
InvitationStatus.DECLINED=Declined
InvitationStatus.PENDING=Pending
InvitationStatus.TENTATIVE=Tentative
InvitationStatus.UNINVITED=Uninvited
musician.voice=Voice
NavigatorLabel=${from}–${to} of ${of}
PageSizeSelector.label=Rows per page
PageSizeSelector.option.all=All
person.emailAddress=Email
person.name=Name
persons=People
signOutLink.body=Sign Out
Voice.ALTO=Alto
Voice.BASS=Bass
Voice.SOPRANO=Soprano
Voice.TENOR=Tenor
