back=Back
close=Close
date=Date
accountSettingsLink.body=Account Settings
event=Event
event.adp.abbrev=Ac/De/Pe
event.adp.full=Accepted/Declined/Pending
event.location=Location
event.summary=Name
EventCreationForm.submit.success=A new event has been added
EventEditForm.submit.success=The event was successfully edited
EventForm.description=Add description
EventForm.details=Details
EventForm.endDateTime=End date
EventForm.location=Add location
EventForm.startDateTime=Start date
EventForm.summary=Add summary
EventForm.to=to
EventTablePanel.create=Create Event
events=Events
InvitationStatus.ACCEPTED=Accepted
InvitationStatus.DECLINED=Declined
InvitationStatus.PENDING=Pending
InvitationStatus.TENTATIVE=Tentative
InvitationStatus.UNINVITED=Uninvited
musician.voice=Voice
NavigatorLabel=${from}–${to} of ${of}
PageSizeSelector.label=Rows per page
PageSizeSelector.option.all=All
person.emailAddress=Email
person.name=Name
persons=People
save=Save
signOutLink.body=Sign Out
Voice.ALTO=Alto
Voice.BASS=Bass
Voice.SOPRANO=Soprano
Voice.TENOR=Tenor
