back=Zurück
close=Schließen
date=Datum
Dropdown.toggle=Dropdown umschalten
accountSettingsLink.body=Accounteinstellungen
event=Event
event.adp.abbrev=An/Ab/Au
event.adp.full=Angenommen/Abgelehnt/Ausstehend
event.createdDate=Erstellt
event.date=Datum
event.description=Beschreibung
event.location=Ort
event.summary=Name
EventCreationForm.submit.success=Ein neues Event wurde hinzugefügt
EventEditForm.submit.success=Das Event wurde erfolgreich bearbeitet
EventForm.description=Beschreibung hinzufügen
EventForm.details=Details
EventForm.endDateTime=Enddatum
EventForm.location=Ort hinzufügen
EventForm.startDateTime=Startdatum
EventForm.summary=Titel hinzufügen
EventForm.to=bis
EventPanel.event.actions=Eventaktionen
EventPanel.event.details=Eventzusammenfassung anzeigen
EventPanel.event.edit=Event bearbeiten
EventTablePanel.create=Neues Event
events=Events
InvitationStatus.ACCEPTED=Angenommen
InvitationStatus.DECLINED=Abgelehnt
InvitationStatus.PENDING=Angenommen
InvitationStatus.TENTATIVE=Vorläufig
InvitationStatus.UNINVITED=Ausstehend
musician.voice=Stimmgruppe
NavigatorLabel=${from}–${to} von ${of}
PageSizeSelector.label=Zeilen pro Seite
PageSizeSelector.option.all=Alle
person.emailAddress=E-Mail-Adresse
person.name=Name
persons=Personen
save=Speichern
signOutLink.body=Abmelden
Voice.ALTO=Alt
Voice.BASS=Bass
Voice.SOPRANO=Sopran
Voice.TENOR=Tenor
