date=Datum
event=Event
event.adp.abbrev=An/Ab/Au
event.adp.full=Angenommen/Abgelehnt/Ausstehend
event.location=Ort
event.summary=Name
events=Events
InvitationStatus.ACCEPTED=Angenommen
InvitationStatus.DECLINED=Abgelehnt
InvitationStatus.PENDING=Angenommen
InvitationStatus.TENTATIVE=Vorläufig
InvitationStatus.UNINVITED=Ausstehend
musician.voice=Stimmgruppe
NavigatorLabel=${from}–${to} von ${of}
PageSizeSelector.label=Zeilen pro Seite
person.name=Name
Voice.ALTO=Alt
Voice.BASS=Bass
Voice.SOPRANO=Sopran
Voice.TENOR=Tenor
