version: '3'

services:
    database:
        image: mysql:5.7
        container_name: participate-db
        restart: always
        ports:
        - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: participate
            MYSQL_USER: participate
            MYSQL_PASSWORD: participate

    fakesmtp:
        image: amontaigu/fakesmtp
        container_name: fakesmtp
        restart: always
        ports:
        - '587:25'
        volumes:
        - $HOME/received-email:/var/mail
