name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up AdoptOpenJDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compile sources
        run: mvn -B compile test-compile
      - name: Run tests
        run: mvn -B test
      - name: Package artifact
        run: mvn -B -fae -DskipTests=true package

      - name: Report Surefire results
        if: always()
        uses: ScaCap/action-surefire-report@v1
