name: Validate and build Anwendung backend with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Validate and Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Compile sources
        run: mvn -B compile test-compile
      - name: Run tests
        run: mvn -B test
      - name: Package artifact
        run: mvn -B -fae -DskipTests=true package

      - name: Report Surefire results
        uses: scacap/action-surefire-report@v1
        if: success() || failure()
